name: Go Build

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          skip-go-installation: true
          # skip-pkg-cache: true
          # skip-build-cache: true
          args: --timeout 2m0s  
      - name: Check documentation
        run: make docs/check
      - name: Build
        run: make binary
      - name: Unit tests
        run: make test/unit
