name: goreleaser

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      # -
        # name: Unshallow
        # run: git fetch
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${GITHUB_REF} =~ ^refs/tags/^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=prerelease::false"
          else
            echo "::set-output name=prerelease::true"
          fi
      - run: echo ${{ steps.check-tag.outputs.prerelease }}
      - 
        name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1
      - 
        name: Generate release notes
        if: steps.check-tag.outputs.prerelease == 'false'
        run: |
          git-chglog -t .chglog/RELEASE.tpl.md $(git describe --tags $(git rev-parse HEAD)) > RELEASE_NOTES.md
     
      - name: Print release notes
        if: steps.check-tag.outputs.prerelease == 'false'
        run: cat RELEASE_NOTES.md

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: steps.check-tag.outputs.prerelease == 'false'
        with:
          version: latest
          args: release --rm-dist --release-notes=RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser on pre-release
        uses: goreleaser/goreleaser-action@v2
        if: steps.check-tag.outputs.prerelease == 'true'
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}